### PR TITLE
minified css now includes proper link styles

### PR DESCRIPTION
**Pull request by shauncore-encore**
noticed that somehow my minified CSS update for links didn't match the regular CSS file, this fixes it

### CODE REVIEW

**Comment by aaronstarkey** [comment]
the diff is huge, cause it's all the css, but can you explain what's
different?

**Comment by shauncore-encore** [comment]
The old minified version incorrectly targeted the article/page body links with:

.article-content a, .entry-content a {…}
.article-content a:hover, .entry-content a:hover {…}

which accidentally formats the sidebar Top Stories links. The new minified version matches the regular CSS file, which correctly declares link rules this way:

article .article-content a, article.page .entry-content a {…}
article .article-content a:hover, article.page .entry-content a:hover {…}

These rules could be simplified of course if there was a consistent element and/or class wrapping the post and page content.

**Comment by aaronstarkey** [comment]
sorry my question was: how did the minified version not match the
non-minified version?

Also, make a proposal for how you'd want to standardize the articles in a
manner that makes sense to you.

i'm totally confident some of that can be refactored a bit as a lot of the
post layout stuff was evolving as we went along.

**Comment by shauncore-encore** [comment]
It must be from running the sass and cssnano commands separately, rather than utilize scss-for-prod. Won’t make that mistake again.

I’ll work on that proposal for article standardization.

On Oct 27, 2017, at 5:38 PM, Aaron Starkey <notifications@github.com<mailto:notifications@github.com>> wrote:

sorry my question was: how did the minified version not match the
non-minified version?

Also, make a proposal for how you'd want to standardize the articles in a
manner that makes sense to you.

i'm totally confident some of that can be refactored a bit as a lot of the
post layout stuff was evolving as we went along.

**Pull request merged**
